#pragma once
enum class UIInteractionEvent
{
	OnSplashScreen1Ended,
	OnSplashScreen2Ended,
	OnSplashScreen3Ended,
	OnValidTokenFound,
	OnPressLogin,
	OnPressRegister,
	OnLoginStatus,
	OnLoadGameData,
	OnSwitchToMainMenu,
	OnPressMultiplayer,
	OnPressCreateLobby,
	OnPressJoinLobby,
	OnJoinedLobby,
	OnRequestDeckData,
	OnParseDecksData,
	OnPressReady,
	OnPressStartGame,
	OnGameCanLoadAssets,
	OnHoverOverCard,
	OnSelectCard,
	OnDeselectCard,
	OnConfirmCard,
	OnPressSubmitCards,
	OnPushCard,
	OnPopCard,
	OnClearDeck,
	OnSetConfirmEnabled,

	OnUpdateHealthPlayer,
    OnUpdateArmorPlayer,
    OnUpdateIconPlayer,
    OnUpdateNamePlayer,
    OnUpdateDiscardPlayer,
    OnUpdateDeckPlayer,
    OnUpdateCardBoxPlayer,

	OnUpdateHealthOpponent,
    OnUpdateArmorOpponent,
    OnUpdateIconOpponent,
    OnUpdateNameOpponent,

	OnUpdateHealthMonster,
	OnUpdateArmorMonster,
	OnUpdateNameMonster,
    OnUpdateIconMonster,

    OnUpdateGameTimer,
    OnUpdateFirstPlayerTag,
	
	OnToggleLoadingScreen,
	OnShowReward,
	OnConfirmReward,
	OnWinScreen,
	OnLoseScreen,
	OnLeaveMatch,

	OnUpdateLoadingScreen,
	Quit,
	OnSwitchToWaitLobby,
	OnBackToLogin,
	OnShowEULA,
	OnRegisterAccount,
	OnPressEULARight,
	OnPressEULALeft,
	OnAudioToggle,
	OnUpdateHandText,
	OnServerDisconnect
};

